# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: skku_i2slab
short_labname: I2SLab
email: i2slab00@gmail.com
logo: logo.png
description: > # 다음 줄에 연구실 소개 입력
  Intelligent and Interactive Systems Lab, Sungkyunkwan University; 성균관대학교 실감미디어공학과 이장원 교수 연구실; Jangwon Lee;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  i2s-lab
google-site-verification:

# Build settings
markdown: kramdown
include: ['_pages', '_news']
plugins: [jekyll-seo-tag,jekyll-paginate]

paginate: 5
paginate_path: "/news/page:num/"
